RUNS_NAME: "ldf_debug"
TB_ROOT: tb_runs_4
SEED: 77
DATA:
  STRONG_AUG: False
SOLVER:
  ROUND_NUM : 2
  WARMUP_EPOCH: 2
  ITER_PER_EPOCH: 8
  EPOCH_PER_ROUND: 2
  
  PSEUDO_UPDATE_POLICY: 'src_half'
  SRC_INIT_PORTION: 0.01
  TGT_INIT_PORTION: 0.01
  TGT_MAX_PORTION: 0.6
  PSE_FILTER_PORTION: 0.05
  ONLY_MASK: True
  PRINT_FREQ: 2
TEST:
  EVAL_INTERVAL: 4